openapi: '3.0.1'
info:
  title: Formatador ABNT
  description:
    O projeto “Formatador de textos para norma ABNT” tem como propósito ajudar o usuário, que em sua maioria são alunos, 
    mas podem ser de variados grupos, a formatar quaisquer texto para os requisitos da ABNT, que são amplamente utilizados em todas as áreas.
  version: '0.1'

servers:
  - url: http://{host}:{porta}/api
    variables:
      host: 
        default: localhost
      porta: 
        default: '8000'

paths:
  /signin:
    get:
      summary: Página de preenchimento de dados de um novo usuário
      responses:
        200:
          description: OK
        404:
          description: Página não encontrada
    post:
      summary: Cria o usuário em questão
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Nome de usuário
                email:
                  type: string
                  description: Email do usuário
                senha:
                  type: string
                  description: Senha do perfil
      responses:
        201:
          description: Usuário criado
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                    description: o URI do novo Usuario
        400:
          description: Requisição inválida
  /login:
    post:
      summary: Entra com um usuário existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email do usuário
                senha:
                  type: string
                  description: Senha do perfil
      responses:
        201:
          description: Usuário logado
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                    description: o URI do usuário logado
        400:
          description: Requisição inválida

  /documentos:
    get:
      summary: Lista de documentos de um usuário
      responses:
        200:
          description: OK
        404:
          description: Página não encontrada
          
  /documento:
    post:
      summary: Cria um novo documento formatado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                texto:
                  type: string
                  description: Texto a ser formatado
                id_usuario:
                  type: string
                  description: Usuário dono do documento
      responses:
        201:
          description: Documento criado
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                    description: o URI do novo Documento
        400:
          description: Requisição inválida

  /documento/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get: 
      summary: Acessa um documento
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object

    put:
      summary: Altera um documento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                texto:
                  type: string
                  description: Texto a ser alterado
      responses:
        200:
          description: OK
        404:
          description: Documento não encontrado
    
    delete:
      summary: Apaga um documento
      responses:
        200:
          description: Ok
        400:
          description: Documento não encontrado    
